FROM alpine

#ENTRYPOINT ["openvpn"]
VOLUME ["/vpn"]
ENTRYPOINT ["openvpn.sh"]
COPY script/openvpn.sh /usr/bin


RUN apk add --no-cache openvpn \
&& echo "net.ipv6.conf.all.disable_ipv6 = 0" >> /etc/sysctl.d\00-alpine.conf \
&& echo "net.ipv6.conf.default.disable_ipv6 = 0" >> /etc/sysctl.d\00-alpine.conf \
&& echo "net.ipv6.conf.lo.disable_ipv6 = 0" >> /etc/sysctl.d\00-alpine.conf \
&& chmod +x /usr/bin/openvpn.sh
